"""الإصدار الأول: كل الجداول

Revision ID: edae89c718f2
Revises: 
Create Date: 2026-09-01 02:39:23.182175
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'edae89c718f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('hk_window', sa.String(length=32), nullable=False),
    sa.Column('desk_status', sa.String(length=16), nullable=False),
    sa.Column('season_auto', sa.Boolean(), nullable=False),
    sa.Column('ramadan_start', sa.Date(), nullable=True),
    sa.Column('ramadan_end', sa.Date(), nullable=True),
    sa.Column('hajj_start', sa.Date(), nullable=True),
    sa.Column('hajj_end', sa.Date(), nullable=True),
    sa.Column('escalation_webhook', sa.Text(), nullable=False),
    sa.Column('wa_phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('wa_access_token', sa.Text(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.Date(), nullable=True),
    sa.Column('billing_status', sa.String(length=16), nullable=False),
    sa.Column('billing_email', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_wa_phone_number_id'), ['wa_phone_number_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('seasons', sa.String(length=64), nullable=False),
    sa.Column('hours', sa.String(length=32), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_fact_tenant_key')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index('ix_fact_tenant_active', ['tenant_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('room', sa.String(length=16), nullable=False),
    sa.Column('group_mode', sa.String(length=16), nullable=False),
    sa.Column('group_rooms', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('checkout_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wa_id', name='uq_guest_tenant_wa')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_wa_id'), ['wa_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('subscription_amount', sa.Integer(), nullable=False),
    sa.Column('overage_messages', sa.Integer(), nullable=False),
    sa.Column('overage_amount', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('vat_amount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_vat', sa.String(length=32), nullable=False),
    sa.Column('zatca_qr', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_invoice_tenant_period')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_staff_email')
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('inbound', sa.Integer(), nullable=False),
    sa.Column('outbound', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.Column('handoffs', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', name='uq_usage_tenant_period')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.String(length=24), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=True),
    sa.Column('sources', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('violations', sa.Text(), nullable=False),
    sa.Column('restricted_category', sa.String(length=32), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_wa_message_id'), ['wa_message_id'], unique=False)
        batch_op.create_index('ix_msg_tenant_time', ['tenant_id', 'created_at'], unique=False)

    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('to', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('guest_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.create_index('ix_handoff_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_handoffs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('room', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('requested_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))
        batch_op.drop_index('ix_ticket_tenant_status')

    op.drop_table('tickets')
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handoffs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_handoffs_reason'))
        batch_op.drop_index(batch_op.f('ix_handoffs_created_at'))
        batch_op.drop_index('ix_handoff_tenant_status')

    op.drop_table('handoffs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_tenant_time')
        batch_op.drop_index(batch_op.f('ix_messages_wa_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_messages_guest_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_period'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_tenant_id'))

    op.drop_table('staff_users')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_period'))

    op.drop_table('invoices')
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_wa_id'))
        batch_op.drop_index(batch_op.f('ix_guests_tenant_id'))

    op.drop_table('guests')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_tenant_id'))
        batch_op.drop_index('ix_fact_tenant_active')

    op.drop_table('facts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_wa_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
